### Null Data Handling

---
Null data is a headache on Data Science's world and it's going to be found several times in our DataFrames

### We create a DataFrame with some null values

In [1]:
import pandas as pd
import numpy as np

In [2]:
dict = {'Col1':[1,2,3,np.nan],
'Col2':[4, np.nan,6,7],
'Col3':['a','b','c', None]}

In [4]:
df = pd.DataFrame(dict)
df

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

### Identifying null values in a DataFrame

In [5]:
df.isnull

<bound method DataFrame.isnull of    Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None>

### Identify null values with a numeric value

In [6]:
df.isnull() * 1

   Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

### Replace null values with a string

In [ ]:
df.isnull('Missing')

### Replace null values with statistical measurement made with the values of the columns

In [8]:
df.fillna(df.mean())

<ipython-input-8-a2478f315f9e>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())

   Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

### Replace null values with interpolated values

In [9]:
df.interpolate()

   Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

### Remove null values

In [10]:
df.dropna()

   Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c