# Pandas 

---
## Pandas is a Python library specialized in the management and analysis of data structures. The name comes from “Panel data”.

*   Speed
*   Optimal use of fewer code lines
*   Multiple file formats
*   Smart alignment

# Pandas series

---
## It is very similar to a NumPy one-dimensional array (or vector).

*   Indexed one-dimensional array
*   Search by index
*   Slicing
*   Arithmetic operations
*   Different types of data

# Pandas DataFrame

---
## Very similar to the matrix structures worked with NumPy.

*   Main structure
*   Two-dimensions array
*   Search by index (columns or rows)
*   Slicing
*   Arithmetic operations
*   Different types of data
*   Variable size

In [1]:
import pandas as pd

### Defining a pandas series with a list

In [7]:
psg_players=pd.Series(['Navas', 'Mbappe', 'Neymar', 'Messi'], 
          index = [1,7,10,30]
          )

In [4]:
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

### Defining Pandas series with a dictionary

In [11]:
psg_dict = {1:'Navas', 7:'Mbappe', 10:'Neymar', 30:'Messi'}
pd.Series(psg_dict)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [16]:
psg_players[7]

'Mbappe'

In [17]:
new_dict = {'Player':['Navas', 'Mbappe', 'Neymar', 'Messi'],
 'Height': [1.85, 178.4, 172.7, 170.0],
 'Scored_Goals':[ 2, 259, 434, 790],
 }

In [20]:
df_players = pd.DataFrame(new_dict, index = [1,7,10,30])
df_players

    Player  Height  Scored_Goals
1    Navas    1.85             2
7   Mbappe  178.40           259
10  Neymar  172.70           434
30   Messi  170.00           790

In [21]:
df_players.columns

Index(['Player', 'Height', 'Scored_Goals'], dtype='object')

In [22]:
df_players.index

Int64Index([1, 7, 10, 30], dtype='int64')

In [23]:
granada = {'Player': ['Luis Suárez','Jorge Molina', 'Antonio Puertas', 'Germán Sánchez', 'Luis Milla', 'Luís Manuel Arantes Maximiano'],
           'Position':['Forward', 'Forward', 'Milfilder', 'Defense', 'Midfilder', 'Goalkeeper'],
           'Number': [9, 7, 8, 3, 11, 1],
           'Scored_Goals': [11,8,5,2,2,1],
           'Height(cm)': [1.85, 1.83,1.79, 1.90, 1.78, 1.94],
           'Yellow_Card': [3, 2, 3, 5, 2, 0],
           'Red_Card': [1, 0, 0, 1, 0, 0]
}

In [25]:
granada_df = pd.DataFrame(granada)
granada_df

,Player,Position,Number,Scored_Goals,Height(cm),Yellow_Card,Red_Card
0,Luis Suárez,Forward,9,11,1.85,3,1
1,Jorge Molina,Forward,7,8,1.83,2,0
2,Antonio Puertas,Milfilder,8,5,1.79,3,0
3,Germán Sánchez,Defense,3,2,1.90,5,1
4,Luis Milla,Midfilder,11,2,1.78,2,0
5,Luís Manuel Arantes Maximiano,Goalkeeper,1,1,1.94,0,0